---
title: "blca_slingshot"
author: "Jing"
date: "2025-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)     
ROOT.DIR <- '/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_monocle/'
DATA.PATH <- file.path(ROOT.DIR, "data", "processed_data.h5")
     
```

```{r}
suppressMessages(library(Matrix))
suppressMessages(library(rhdf5))
suppressMessages(library(monocle3))
# Read matrix
barcodes <- h5read(DATA.PATH, "expression_matrix/barcodes")
features <- h5read(DATA.PATH, "expression_matrix/features")
data <- h5read(DATA.PATH, "expression_matrix/data")
indices <- h5read(DATA.PATH, "expression_matrix/indices")
indptr <- h5read(DATA.PATH, "expression_matrix/indptr")

expr.mtx <- Matrix::sparseMatrix(
  i=indices, p=indptr, x=as.numeric(data),
  dimnames=list(as.character(features), as.character(barcodes)),
  index1=FALSE, repr="C")

# Read parameters
umap <- t(h5read(DATA.PATH, "UMAP"))
leiden <- h5read(DATA.PATH, "Leiden")


# Create cell_data_set
cds <- new_cell_data_set(expr.mtx)

# UMAP
rownames(umap) <- barcodes
cds@int_colData@listData$reducedDims@listData[["UMAP"]] <- umap

umap <- as.matrix(umap)
rownames(umap) <- colnames(cds)  # Important for matching

reducedDims(cds)$UMAP <- umap

## Clusters
names(leiden) <- cds@colData@rownames
leiden <- as.factor(leiden)
cds@clusters@listData[["UMAP"]][["clusters"]] <- leiden

rowData(cds)$gene_short_name <- row.names(rowData(cds))
cds@colData$cluster <- as.factor(leiden)

```

